src/app/Components/home/home.component.html
src/app/Components/home/home.component.ts
src/app/Services/tts.service.ts

close #13
added vorlesen to home

added TTSService

---

src/app/Components/home/home.component.html
src/app/Components/home/home.component.spec.ts
src/app/Components/home/home.component.ts
src/app/Services/speechrecognition.service.ts
src/app/Services/tts.service.ts
src/app/app.module.ts

SpeechRecognitionService

---

src/app/Components/home/home.component.css
src/app/Components/home/home.component.html
src/app/Components/home/home.component.spec.ts
src/app/Components/home/home.component.ts
src/app/Objects/command.ts
src/app/Services/database.service.ts
src/app/app.module.ts
src/index.html

command input via keyboard or speech.
response output via display or tts.
fixed #16
close #3

Send command to Amy and display response

---

.docker/dockerize-templates/httpd.conf.tmpl
.gitignore
Dockerfile
README.md
src/.dockerignore

Add a Dockerfile and some additional files for Docker.
Completes Web App as Dockercontainer in https://github.com/AmyAssist/Amy/issues/166

Basic Docker ability

---

src/app/Plugins/Music/Components/music/music.component.html
src/app/Plugins/Music/Components/music/music.component.ts
src/app/Plugins/Music/Objects/music.ts
src/app/Plugins/Weather/Components/weather/weather.component.ts
src/app/Plugins/Weather/Objects/location.ts

spotify current song fix

---

src/app/Plugins/Registry/Components/location-registry/location-registry.component.ts
src/app/Services/speechrecognition.service.ts

goolge speech time output is now format to hh x mm am/pm to match with grammars in the server (google is too smart for out grammars)

New Google Speech time output

---

package.json
src/app/Plugins/Clock/Components/clock/clock.component.ts
src/app/Plugins/Clock/Services/clock-data.service.ts
src/app/Plugins/Music/Components/music/music.component.ts
src/app/Plugins/Music/Services/music-data.service.ts
src/app/Plugins/Music/music-routing.module.ts
src/app/Plugins/Navigation/Components/navigation/navigation.component.spec.ts
src/app/Plugins/Navigation/Components/navigation/navigation.component.ts
src/app/Plugins/Navigation/Services/navigation-data.service.spec.ts
src/app/Plugins/Navigation/Services/navigation-data.service.ts
src/app/Plugins/Registry/Components/contact-registry/contact-registry.component.ts
src/app/Plugins/Registry/Components/location-registry/location-registry.component.ts
src/app/Plugins/Registry/Services/contact-registry-data.service.ts
src/app/Plugins/Registry/Services/location-registry-data.service.ts
src/app/Plugins/Weather/Components/weather/weather.component.ts
src/app/Plugins/Weather/Services/weather-data.service.ts

fixed music backend path
Additional:
* removed unused import
* fixed route authentification in music

fixed music backend path

---

package-lock.json
package.json
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.module.ts
src/app/material.module.ts

added responsive design for toolbar

responsive toolbar

---

src/app/Plugins/Music/Components/music/music.component.ts
src/app/Plugins/Weather/Components/weather/weather.component.css
src/app/Plugins/Weather/Components/weather/weather.component.html

scale cards correctly and a minor spotify fix

several quick fixes

---

src/app/Components/home/home.component.html
src/app/Components/home/home.component.ts

Make speech input in web app smoother

---

src/app/app.component.css
src/app/app.component.html

Made main content responsive

---

.docker/.htaccess
.docker/dockerize-templates/httpd.conf.tmpl
Dockerfile

this is required for the single page application

added .htaccess

---

package-lock.json
src/app/Plugins/Registry/Components/contact-registry/contact-registry.component.html
src/app/Plugins/Registry/Components/contact-registry/contact-registry.component.ts
src/app/Plugins/Registry/Components/contact-registry/contact-validator.service.ts
src/app/Plugins/Registry/Components/location-registry/location-registry.component.html
src/app/Plugins/Registry/Components/location-registry/location-registry.component.ts

Registry tags

---

src/app/Components/amy-chat/amy-chat.component.css
src/app/Components/amy-chat/amy-chat.component.html
src/app/Components/amy-chat/amy-chat.component.ts
src/app/Services/speechrecognition.service.ts

fixed #71 
only show SR button if it is supported

Browser compatibility

---

package-lock.json
src/app/Plugins/Music/Components/content/content.component.ts
src/app/Plugins/Music/Components/current-song/current-song.component.ts
src/app/Plugins/Music/Components/music/music.component.html
src/app/Plugins/Music/Objects/item.ts
src/app/Plugins/Music/Objects/music.ts
src/app/Plugins/Music/Services/music-data.service.ts

song entity now also has an imageURL it can request and the order of the elements in the responsive musicUI is changed to currentSong is on top on smaller devices

imageURL and responsive order

---

src/app/Plugins/Music/Components/content/content.component.ts
src/app/Plugins/Music/Components/current-song/current-song.component.ts
src/app/Plugins/Music/Components/sidebar/sidebar.component.ts
src/app/Plugins/Music/Services/music-data-transfer.service.ts

Set refresh with currentSong in Components/current-song/current-song.component.ts to every second and fixed a bug with a missing imageUrl when the song isnt started in the webUI.

CurrentSong Refresh and bugfix

---

src/app/Plugins/Email/Components/messagelist/messagelist.component.css
src/app/Plugins/Email/Components/messagelist/messagelist.component.html
src/app/Plugins/Email/Components/messagelist/messagelist.component.ts
src/app/Plugins/Email/Objects/MessageDTO.ts

Removed panels and content - added sent date

---

src/app/Plugins/Calendar/Components/new-event/new-event.component.ts

If I want to make a new all day event for today it also had yesterday as part of the event. Now it is fixed.

Fixing a problem with all day events

---

src/app/Plugins/Clock/clock-routing.module.ts
src/app/Plugins/Clock/clock.module.ts
src/app/Plugins/Email/email-routing.module.ts
src/app/Plugins/Email/email.module.ts
src/app/Plugins/Timer/timer-routing.module.ts
src/app/Plugins/Timer/timer.module.ts
src/app/app.module.ts

modules for plugins email, timer and clock

---

src/app/Components/push/push.component.css
src/app/Components/push/push.component.html
src/app/Components/push/push.component.ts
src/app/Services/pushNotification.service.ts

added error feedback
added success feedback

added processing indicator to push setup

---

src/app/Plugins/Registry/Components/contact-registry/contact-registry.component.ts
src/app/Plugins/Registry/Components/location-registry/location-registry.component.ts
src/app/Plugins/Registry/Components/registry-container/registry-container.component.html
src/app/Plugins/Registry/Services/contact-registry-data.service.ts

Fix some wrong declarations in the contact and location registry

Refactor Registry

---

src/app/Plugins/Weather/Components/weather/weather.component.html

removed code that caused the weatherUI to be not centered

---

package.json
src/app/Components/Home/Home-Components/home/home.component.ts
src/app/Components/Home/Home-Components/messages-container/messages-container.component.css
src/app/Components/Home/Home-Components/messages-container/messages-container.component.html
src/app/Components/Home/Home-Components/messages-container/messages-container.component.spec.ts
src/app/Components/Home/Home-Components/messages-container/messages-container.component.ts
src/app/Components/Home/Home-Objects/message.ts
src/app/Components/Home/Home-Objects/response.ts
src/app/Components/Home/Home-Services/chat.service.ts
src/app/Components/Home/Home-Services/command-handler.service.ts
src/app/Plugins/Music/music.module.ts
src/app/Plugins/Navigation/Components/route-widget/route-widget.component.css
src/app/Plugins/Navigation/Components/route-widget/route-widget.component.html
src/app/Plugins/Navigation/Components/route-widget/route-widget.component.ts
src/app/Plugins/Navigation/Objects/routeWidgetInfo.ts
src/app/Plugins/Navigation/navigation.module.ts
src/app/Plugins/Weather/Components/day/day.component.css
src/app/Plugins/Weather/Components/day/day.component.html
src/app/Plugins/Weather/Components/day/day.component.ts
src/app/Plugins/Weather/Components/weather/weather.component.html
src/app/Plugins/Weather/Components/weather/weather.component.ts
src/app/Plugins/Weather/Objects/weatherReportDay.ts
src/app/Plugins/Weather/Objects/weatherReportInstant.ts
src/app/Plugins/Weather/weather.module.ts

Corresponding Backend-PR: AmyAssist/Amy#467

Rich replies
